[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''elseif self.ability.name == 'Mime' then'''
position = 'at'
match_indent = true
payload = '''elseif self.ability.name == 'Mime' then loc_vars = {
    self.ability.extra,
    (self.ability.extra ~= 1 and "s" or ""),
}'''