[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''local jokers_to_create = math.min(2, G.jokers.config.card_limit - (#G.jokers.cards + G.GAME.joker_buffer))'''
position = 'at'
match_indent = true
payload = '''local jokers_to_create = math.min(self.ability.extra, G.jokers.config.card_limit - (#G.jokers.cards + G.GAME.joker_buffer))'''