[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''j_superposition=    {order = 59,  unlocked = true,  discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 1, cost = 4, name = 'Superposition', pos = {x = 3, y = 11}, set = 'Joker', config = {}},'''
position = 'at'
match_indent = true
payload = '''j_superposition=    {order = 59,  unlocked = true,  discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 1, cost = 4, name = 'Superposition', pos = {x = 3, y = 11}, set = 'Joker', config = {extra = 1}},'''


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''elseif self.ability.name == 'Superposition' then loc_vars = {self.ability.extra}'''
position = 'at'
match_indent = true
payload = '''elseif self.ability.name == 'Superposition' then loc_vars = {
    self.ability.extra,
    (self.ability.extra ~= 1 and "s" or ""),
}'''

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.name == 'Superposition' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
    local aces = 0
    for i = 1, #context.scoring_hand do
        if context.scoring_hand[i]:get_id() == 14 then aces = aces + 1 end
    end
    if aces >= 1 and next(context.poker_hands["Straight"]) then
        local card_type = 'Tarot'
        G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
        G.E_MANAGER:add_event(Event({
            trigger = 'before',
            delay = 0.0,
            func = (function()
                    local card = create_card(card_type,G.consumeables, nil, nil, nil, nil, nil, 'sup')
                    card:add_to_deck()
                    G.consumeables:emplace(card)
                    G.GAME.consumeable_buffer = 0
                return true
            end)}))
        return {
            message = localize('k_plus_tarot'),
            colour = G.C.SECONDARY_SET.Tarot,
            card = self
        }
    end
end'''
position = 'at'
match_indent = true
payload = '''if self.ability.name == 'Superposition' then
    local aces = 0
    for i = 1, #context.scoring_hand do
        if context.scoring_hand[i]:get_id() == 14 then aces = aces + 1 end
    end
    if aces >= 1 and next(context.poker_hands["Straight"]) then
        local added_cards_amount = 0
        for i = 1, self.ability.extra do
            if #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
                added_cards_amount = added_cards_amount + 1
                G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
                G.E_MANAGER:add_event(Event({
                    trigger = 'before',
                    delay = 0.0,
                    func = (function()
                            local card = create_card("Tarot",G.consumeables, nil, nil, nil, nil, nil, 'sup')
                            card:add_to_deck()
                            G.consumeables:emplace(card)
                            G.GAME.consumeable_buffer = 0
                        return true
                    end)}))
            end
        end
        return {
            message = "+"..added_cards_amount..string.sub(localize('k_plus_tarot'), 3, -1),
            colour = G.C.SECONDARY_SET.Tarot,
            card = self
        }
    end
end'''